default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  primary:
    <<: *default
    database: mi_classrooms_development
  queue:
    <<: *default
    database: mi_classrooms_queue_development
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: mi_classrooms_cable_development
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    database: mi_classrooms_test
  queue:
    <<: *default
    database: mi_classrooms_queue_test
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: mi_classrooms_cable_test
    migrations_paths: db/cable_migrate

staging:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  queue:
    <<: *default
    url: <%= ENV["DATABASE_QUEUE_URL"].presence || ENV["DATABASE_URL"] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    url: <%= ENV["DATABASE_CABLE_URL"].presence || ENV["DATABASE_URL"] %>
    migrations_paths: db/cable_migrate

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  queue:
    <<: *default
    url: <%= ENV["DATABASE_QUEUE_URL"].presence || ENV["DATABASE_URL"] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    url: <%= ENV["DATABASE_CABLE_URL"].presence || ENV["DATABASE_URL"] %>
    migrations_paths: db/cable_migrate
